fix: update tis status when gmc outcome update
Health-Education-England/tis-revalidation-recommendation pull request #310
Opened 2021-11-30 12:40 UTC by CaiWillis

Objective is to ensure tis status (i.e. DoctorsForDB.doctorStatus) is updated when recommendation details page is loaded

I've put the check in what I think is the best place, given that this part of the service is fairly "spaghetti-ish" with lots of side-effects - open to suggestions on better placement that doesn't require major refactor

2021-11-30 12:51 UTC, JosephKelly requested changes
Let's add a couple of tests to ensure we are updating doctors appropriately.

2021-11-30 12:51 UTC, JosephKelly commented on application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceImpl.java
> +
It looks like the log statement above this relates to the code below.  I'd consider moving this above as it is not.

2021-11-30 13:26 UTC, jayanta2018 submitted a review, later dismissed
LGTM
On a seperate note the methods "getCurrentAndLegacyRecommendation", "checkRecommendationStatus" are saving stuffs in DBs, which does not go with their names. Is it possible to come up with reasonable names for them? Just a thought though.

2021-12-02 11:06 UTC, JosephKelly approved these changes

2021-12-02 11:06 UTC, merged