Feat/cron recommendation status
Health-Education-England/tis-revalidation-recommendation pull request #313
Opened 2021-12-06 17:11 UTC by DorisWongNHS

- would need to rebase from master
- rabbit queue names may need to be changed

2021-12-06 19:51 UTC, DorisWongNHS commented on lombok.config
> +lombok.addLombokGeneratedAnnotation = true
Config file is added to stop sonar complaining the `@data` test coverage 
https://medium.com/@mladen.bolic/lombok-data-improve-your-code-coverage-a74fb624a72b

2021-12-07 16:06 UTC, JosephKelly requested changes
Thanks for adding the comment! about Lombok & Sonar! I had wondered.

2021-12-08 11:55 UTC, DorisWongNHS commented on application/src/main/java/uk/nhs/hee/tis/revalidation/service/RecommendationServiceImpl.java
> +    List<Recommendation> recommendations = recommendationRepository
Thanks, it is updated to use `getRecommendationStatusCheckDtos().forEach...` 
For the "doctorsForDb.isEmpty()" issue, there are lots of the recommendation would not have a matched doctorsForDB (many of them are migrated from the existing reval). I choose to do nothing for trainees not in doctorsForDB, as the system only count the trainee which is active in GMC which will have a record in doctorsForDB.

2021-12-08 11:55 UTC, DorisWongNHS commented on application/src/main/resources/application.yml
> +    reval.exchange.recommendationstatuscheck: ${REVAL_RABBIT_EXCHANGE_RECOMMENDATION_STATUS_CHECK:reval.exchange.recommendationstatuscheck}
I have removed the line for `reval.exchange.recommendationstatuscheck` as we will use the `reval.exchange` instead.

2021-12-08 11:55 UTC, DorisWongNHS commented on application/src/main/resources/application.yml
> +    cronExpression: ${CRON_EXPRESSION:0 0 * * * *}
I have changed it to use `app.gmc.recommendationstatuscheck.cronExpression`. It contains the keyword of the event, hope it is clearer.

2021-12-08 11:55 UTC, DorisWongNHS commented on application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcClientService.java
> +
It is changed to use the `app.rabbit.reval.exchange instead.

2021-12-08 11:56 UTC, DorisWongNHS commented on application/src/main/java/uk/nhs/hee/tis/revalidation/service/GmcClientService.java
> +    List<RecommendationStatusCheckDto> recommendations = recommendationService.getRecommendationStatusCheckDtos();
It is updated. Cheers.

2021-12-09 09:06 UTC, JosephKelly approved these changes

2021-12-10 09:36 UTC, merged