fix: set under notice to no when disconnecting a doctor
Health-Education-England/tis-revalidation-recommendation pull request #462
Opened 2023-09-27 13:11 UTC by CaiWillis

TIS21-5014: Set underNotice to NO when disconnecting a doctor

2023-09-28 10:04 UTC, hihilary submitted a review, later dismissed

2023-09-28 10:23 UTC, JosephKelly commented on application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
> +      if(dbc == null) doctorsForDB.setUnderNotice(NO);
We evaluate whether DBC is null twice.  I would guess that the compiler isn't smart enough to reduce the number of evaluations here... It's worth thinking about the trade off in increased LOC & additional processing.

It's a tiny difference at this scale but we should try and do the optimal thing.

2023-09-28 10:24 UTC, JosephKelly requested changes

2023-09-28 10:24 UTC, JosephKelly commented on application/src/main/java/uk/nhs/hee/tis/revalidation/service/DoctorsForDBService.java
> +import uk.nhs.hee.tis.revalidation.entity.UnderNotice;
Import is actually unused.  See static imports.

2023-10-04 08:35 UTC, hihilary approved these changes

2023-10-04 14:46 UTC, JosephKelly approved these changes
I want to note (for users) that we aren't able to explicitly set the 'under notice' flag.  I'd like to do 1 of several things about that.  It's related but I'm confident at least 1 wouldn't make the top of the backlog.

2023-10-04 14:47 UTC, merged