Feat/add gmc updated date time for doctor
Health-Education-England/tis-revalidation-recommendation pull request #471
Opened 2023-11-14 01:04 UTC by hihilary

2023-11-14 14:11 UTC, JosephKelly commented on application/src/main/java/uk/nhs/hee/tis/revalidation/mapper/DoctorsForDbMapper.java
> +  @Mapping(target = "doctorStatus", constant = "NOT_STARTED")
I think these were shortcuts and reflect things that the Mapper client should decide but there are implications for a number of methods and probably across services.  Do you think this is Tech Improvement to follow?

2023-11-15 13:03 UTC, JosephKelly requested changes
No idea why the import wasn't a code smell but :shrug:

2023-11-15 13:24 UTC, hihilary commented on application/src/test/java/uk/nhs/hee/tis/revalidation/mapper/DoctorsForDbMapperTest.java
> +import static org.junit.jupiter.api.Assertions.assertNotNull;
Nice spot!

2023-11-15 13:29 UTC, JosephKelly approved these changes

2023-11-15 13:30 UTC, merged