fix:objectMapper config for sqs
Health-Education-England/tis-revalidation-recommendation pull request #480
Opened 2023-12-08 16:00 UTC by hihilary

We added a new datetime in DoctorsForDBDto a few weeks ago, so have to add this config for sqs, otherwise Reval MongoDB -> ES will fail.

TIS21-4657

2023-12-08 16:38 UTC, JosephKelly requested changes

2023-12-08 16:39 UTC, hihilary commented on application/src/main/java/uk/nhs/hee/tis/revalidation/config/RabbitConfig.java
>      return new Jackson2JsonMessageConverter(mapper);
Yes! I was too rushed to remove them.

2023-12-11 12:34 UTC, JosephKelly approved these changes

2023-12-11 13:32 UTC, jayanta2018 commented on application/src/main/java/uk/nhs/hee/tis/revalidation/config/RabbitConfig.java
> +    return new Jackson2JsonMessageConverter(objectMapper);
The changes are here. I noticed.

2023-12-11 13:33 UTC, jayanta2018 approved these changes

2023-12-11 13:33 UTC, merged